name: test3
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.8
  firebase_ui_localizations: ^1.13.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  flutter_quill: ^11.4.1
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/Dmail.png
    - assets/images/avatar1.webp
    - assets/images/avt2.png
    - assets/images/avt3.png
    - assets/images/avt4.png
    - assets/images/avt5.png
    - assets/images/avt6.png

 