// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgCqtkzTHZfaBR424QfbB78u2wO1hDVDg',
    appId: '1:210173845818:web:179be48a9bc32c13047003',
    messagingSenderId: '210173845818',
    projectId: 'test3-3195c',
    authDomain: 'test3-3195c.firebaseapp.com',
    storageBucket: 'test3-3195c.firebasestorage.app',
    measurementId: 'G-WV93WPQLRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPfIfcXbwSdlz9ivAahWf6Ey09O6Dr2A',
    appId: '1:210173845818:android:7fe92e2f99ef8f45047003',
    messagingSenderId: '210173845818',
    projectId: 'test3-3195c',
    storageBucket: 'test3-3195c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB95jcHLsxFeqaHSZfuD--vTH9JakGt7U',
    appId: '1:210173845818:ios:8f2e65acc3424629047003',
    messagingSenderId: '210173845818',
    projectId: 'test3-3195c',
    storageBucket: 'test3-3195c.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB95jcHLsxFeqaHSZfuD--vTH9JakGt7U',
    appId: '1:210173845818:ios:8f2e65acc3424629047003',
    messagingSenderId: '210173845818',
    projectId: 'test3-3195c',
    storageBucket: 'test3-3195c.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgCqtkzTHZfaBR424QfbB78u2wO1hDVDg',
    appId: '1:210173845818:web:5fa4a68aae8d19d9047003',
    messagingSenderId: '210173845818',
    projectId: 'test3-3195c',
    authDomain: 'test3-3195c.firebaseapp.com',
    storageBucket: 'test3-3195c.firebasestorage.app',
    measurementId: 'G-3SD27TQ2LG',
  );

}